syntax = "proto3";

package proto.v1;

import "validate/validate.proto";

option go_package = "github.com/gnbaviskar2207/ecom-products-ms/gen/products;productsV1";

// ProductService is the service for product-related operations
service ProductService {
  // FindOneByPid finds a product by its product id
  rpc FindOneByPid(FindOneByPidRequest) returns (FindOneByPidResponse);
  // ListProducts finds and responds paginated products
  rpc ListProducts(ListProductsRequest) returns (ListProductsResponse);
}

// FindOneByPidResponse represents a response to find a product by its product id
message FindOneByPidResponse {
  Product product = 1;
}

// ListProductsRequest represents a request to find products
message ListProductsRequest {
  string next_cursor = 1 [(validate.rules).string = {max_len: 256}];
  int64  limit       = 2 [(validate.rules).int64 = {gte: 2, lte: 20}];
}

// ListProductsResponse represents a response to find products by their product ids
message ListProductsResponse {
  repeated Product products    = 1;
  string           next_cursor = 2;
  bool             has_more    = 3;
}

// FindOneByPidRequest represents a request to find a product by its product id
message FindOneByPidRequest {
  string pid = 1 [(validate.rules).string = {min_len: 10, max_len: 64}];
}

// Product represents a product in the catalogue
message Product {
  string          pid                    = 1;
  string          name                   = 2;
  string          sku                    = 3;
  string          image                  = 4;
  string          weight                 = 5;
  string          type                   = 6;
  string          category_name          = 7;
  string          sell_price             = 8;
  string          remark                 = 9;
  bool            is_free_shipping       = 10;
  bool            is_video               = 11;
  int64           sale_status            = 12;
  int64           listed_num             = 13;
  string          supplier_name          = 14;
  string          supplier_id            = 15;
  string          category_id            = 16;
  string          source_from            = 17;
  repeated string shipping_country_codes = 18;
  string          three_category_name    = 19;
  string          two_category_id        = 20;
  string          two_category_name      = 21;
  string          one_category_id        = 22;
  string          one_category_name      = 23;
  int64           customization_version  = 24;
  bool            is_test_product        = 25;
}
