services:
  ecom-product-service:
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile.local

    image: localhost/ecom-product-service:local
    container_name: ecom-product-service-local

    ports:
      - "50051:50051"
      - "9091:9091"

    # volumes:
    #   - ../..:/workspace:Z

    restart: unless-stopped

    environment:
      ENVIRONMENT: development
